Model registry cleanup
SNEWS2/snewpy pull request #230
Opened 2022-11-11 23:36 UTC by JostMigenda

This fixes #224. Two things I want to highlight in particular:
* It implements [this suggestion](https://github.com/SNEWS2/snewpy/pull/184/files/d1dfec61831006f5dc9143043a84ba552cb1f27f#r824553338) by @Sheshuk to move the parameter checking into the appropriate base class
* It removes the `Model.param_combinations` property in favour of `Model.get_param_combinations()` (which already existed anyway). In addition to saving some boilerplate code, this is also more extensible. For example, I could imagine adding the ability to give additional arguments like `get_param_combinations(eos='shen')` to narrow the list down.

During the review, please note that thus far, I’ve only updated `Nakazato_2013.ipynb` with the new model initialisation. Let me know if that looks reasonable; if so, I will update
- [ ] the notebooks for all other models and
- [ ] the [Getting Started](https://snewpy.readthedocs.io/en/stable/gettingstarted.html) page of the documentation

before we can merge this PR.

2022-11-17 20:01 UTC, sgriswol requested changes
This looks great! The comments I have should be very easy to address. The most important one being, I think `snewpy.models._init_model` should be public-facing. Is there a reason it is named with a leading underscore?

2022-11-17 20:27 UTC, JostMigenda commented
> `snewpy.models._init_model` should be public-facing.

Eventually, yes. But for now, I think it’s not yet ready—see #225. For this PR, I just wanted to move that out of the `util.py` file so I could delete that as part of the cleanup.

2022-11-22 23:36 UTC, sgriswol requested changes
Thanks for putting this all together @JostMigenda! I have a few comments, most of which are cosmetic and should be easy to address. 
- [ ] The citation links `OConnor_2013.ipynb` , `Zha_2021.ipynb`, and `Warren_2020.ipynb` are missing.
- [ ] The output of code cell  3 in `Nakazato_2013.ipynb` is rather hard to read. 
- [ ] The population of valid `eos` and `progenitor_mass` parameters in the docstring of `snewpy.models.ccsn.OConnor_2013` isn't happening because [python/snewpy/models/ccsn.py:415](https://github.com/SNEWS2/snewpy/blob/dd4b05593aadadcce12f60cd1f3bbb72ef981adb/python/snewpy/models/ccsn.py#L415) is commented.
- [ ] In many of the example notebooks I received a warning over importing from `snewpy.models` rather than `snewpy.models.ccsn`. I have added suggestions to change most notebooks, but I was unable to make a suggestion for `Fornax_2019.ipynb` or `OConnor_2013.ipynb`

I will push a commit shortly to address these comments, aside from the suggestions I was able to make as part of the review (apologies for the mixed formats!).

2022-11-23 01:14 UTC, sgriswol approved these changes
Looks good to me!

2022-11-23 08:46 UTC, merged